import type { Metadata } from "next";
import "./globals.css";
import Transition from "@/components/Transition";
import IssueProvider from "./utils/IssueContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export interface LayoutProps{
  children: React.ReactNode;  // The children component to be rendered in the layout.
}
export default function RootLayout(
  {children}:LayoutProps
) {
  
  return (
    <html lang="en">
      <IssueProvider>
        <body>
          <Transition>
            {children}
          </Transition>
        </body>
        </IssueProvider>
    </html>
  );
}
